### ISSUE TITLE
Can't run a job that accesses code in a module that isn't available in the container

### ISSUE THREAD

**Issue by jared-maguire** [jared-maguire/jobs#5]
Title says it all; here's an example:

``` python
In [3]: import example_workflow as ex

In [4]: ex.ngs_workflow("batch-1")
wf_job: job-lvagd
```

``` bash
(base) jobs% kubectl logs job-lvagd-lvcqq
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/app/module/k8s/k8s.py", line 44, in deserialize_func
    func = pickle.loads(base64.b64decode(code))
  File "/opt/conda/lib/python3.9/site-packages/dill/_dill.py", line 387, in loads
    return load(file, ignore, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/dill/_dill.py", line 373, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/opt/conda/lib/python3.9/site-packages/dill/_dill.py", line 646, in load
    obj = StockUnpickler.load(self)
  File "/opt/conda/lib/python3.9/site-packages/dill/_dill.py", line 636, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'example_workflow'
(base) jobs%
```

Admittedly, when I wrote the title of this issue, it started sounding more like "well, duh, of course" than an actual issue. Maybe it's a reasonable and unavoidable limitation?

**Comment by jared-maguire** [comment]
well, duh, of course. closing.
